# The Academy Awards, 1927 - 2023

Este [dataset](https://www.kaggle.com/datasets/unanimad/the-oscar-award) contiene un scraping de la base de datos de los Premios de la Academia, registros de los nominados y ganadores desde 1927 hasta 2023.

En este EDA cruzaré los datos de diferentes datasets de las películas con las nominadas y ganadoras a mejor pelicula para ver si los miembros de la academia siguen algun tipo de patron o *bias* para elegir la ganadora.

In [45]:
import pandas as pd

Bicheando el df original

In [46]:
df_oscars = pd.read_csv("./data/the_oscar_award.csv")
df_oscars

,year_film,year_ceremony,ceremony,category,name,film,winner
0,1927,1928,1,ACTOR,Richard Barthelmess,The Noose,False
1,1927,1928,1,ACTOR,Emil Jannings,The Last Command,True
2,1927,1928,1,ACTRESS,Louise Dresser,A Ship Comes In,False
3,1927,1928,1,ACTRESS,Janet Gaynor,7th Heaven,True
4,1927,1928,1,ACTRESS,Gloria Swanson,Sadie Thompson,False
...,...,...,...,...,...,...,...
10760,2022,2023,95,HONORARY AWARD,"To Euzhan Palcy, a masterful filmmaker who bro...",NaN,True
10761,2022,2023,95,HONORARY AWARD,"To Diane Warren, for her genius, generosity an...",NaN,True
10762,2022,2023,95,HONORARY AWARD,"To Peter Weir, a fearless and consummate filmm...",NaN,True
10763,2022,2023,95,GORDON E. SAWYER AWARD,Iain Neil,NaN,True
10764,2022,2023,95,AWARD OF COMMENDATION,To Ryan Laney for his innovative adaptation an...,Welcome to Chechnya,True

Me quedo con las categorias de mejor película

In [47]:
BEST_PICTURE = df_oscars.category == "BEST PICTURE"
OUTSTANDING_PICTURE =  df_oscars.category == "OUTSTANDING PICTURE"
OUTSTANDING_PRODUCTION = df_oscars.category == "OUTSTANDING PRODUCTION"
OUSTANDING_MOTION_PICTURE = df_oscars.category == "OUTSTANDING MOTION PICTURE"
BEST_MOTION_PICTURE = df_oscars.category == "BEST MOTION PICTURE"

df_best_picture = df_oscars[BEST_PICTURE | OUTSTANDING_PICTURE | OUTSTANDING_PRODUCTION | OUSTANDING_MOTION_PICTURE | BEST_MOTION_PICTURE]
df_best_picture.drop(columns="category", inplace=True)

C:\Users\Nur\AppData\Local\Temp\ipykernel_14596\3561247230.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_best_picture.drop(columns="category", inplace=True)

In [48]:
df_best_picture[df_best_picture.winner == True]

,year_film,year_ceremony,ceremony,name,film,winner
21,1927,1928,1,Paramount Famous Lasky,Wings,True
64,1928,1929,2,Metro-Goldwyn-Mayer,The Broadway Melody,True
100,1929,1930,3,Universal,All Quiet on the Western Front,True
140,1930,1931,4,RKO Radio,Cimarron,True
178,1931,1932,5,Metro-Goldwyn-Mayer,Grand Hotel,True
...,...,...,...,...,...,...
10219,2018,2019,91,"Jim Burke, Charles B. Wessler, Brian Currie, P...",Green Book,True
10350,2019,2020,92,"Kwak Sin Ae and Bong Joon Ho, Producers",Parasite,True
10474,2020,2021,93,"Frances McDormand, Peter Spears, Mollye Asher,...",Nomadland,True
10591,2021,2022,94,"Philippe Rousselet, Fabrice Gianfermi and Patr...",CODA,True
10718,2022,2023,95,"Daniel Kwan, Daniel Scheinert and Jonathan Wan...",Everything Everywhere All at Once,True

|columna|descripcion|
|-|-|
|year_film|Año de estreno|
|year_ceremony| Año en de la gala|
|ceremony|Número de ceremonia|
|name|Nombre de la productora/los productores|
|film|Título de la película|
|winner|Bool True si ganó|

In [49]:
df_best_picture.to_csv("./data/best_picture.csv", index=False)